# Generated by Django 5.0.6 on 2024-06-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=20)),
                ('descroption', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=300)),
            ],
        ),
    ]
